#!/usr/bin/python
# -*- coding: UTF-8 -*-

'''
Created on Oct 31,2017

@author: hadoop
'''

from datetime import datetime
from utils.time_utils import get_alert_interval
from utils.log import log

# stock_pool = {
#     "002352" : {"name":"顺风控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
#     "002294" : {"name":"信立泰  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
#     "600887" : {"name":"伊利股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},	 
# 	"600298" : {"name":"安琪酵母","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},	
# 	"000895" : {"name":"双汇集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600104" : {"name":"上汽集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600572" : {"name":"康恩贝  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600276" : {"name":"恒瑞医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600566" : {"name":"济川药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000538" : {"name":"云南白药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601318" : {"name":"中国平安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600056" : {"name":"中国医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"603288" : {"name":"海天味业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002027" : {"name":"分众传媒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000581" : {"name":"威孚高科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600741" : {"name":"华域汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000858" : {"name":"五粮液  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600519" : {"name":"贵州茅台","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002422" : {"name":"科伦药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002081" : {"name":"金螳螂  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002470" : {"name":"金正大  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002517" : {"name":"恺英网络","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"300549" : {"name":"优德精密","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"603520" : {"name":"司立太  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600176" : {"name":"中国巨石","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002008" : {"name":"大族激光","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002745" : {"name":"木林森  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600585" : {"name":"海螺水泥","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002372" : {"name":"伟星新材","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600900" : {"name":"长江电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601006" : {"name":"大秦铁路","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600518" : {"name":"康美药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002202" : {"name":"金凤科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002310" : {"name":"东方园林","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000963" : {"name":"华东医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601933" : {"name":"永辉超市","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002466" : {"name":"天齐锂业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002475" : {"name":"立讯精密","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002241" : {"name":"歌尔股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600196" : {"name":"复星医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002572" : {"name":"索菲亚  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600816" : {"name":"安信信托","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002415" : {"name":"海康威视","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000333" : {"name":"美的集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002508" : {"name":"老板电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600660" : {"name":"福耀玻璃","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600201" : {"name":"生物股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000002" : {"name":"万科股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002450" : {"name":"康得新  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600009" : {"name":"上海机场","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600377" : {"name":"宁沪高速","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002597" : {"name":"金禾实业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601012" : {"name":"隆基股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000725" : {"name":"京东方  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600703" : {"name":"三安光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600699" : {"name":"均胜电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600036" : {"name":"招商银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601888" : {"name":"中国国旅","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600019" : {"name":"宝钢股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600352" : {"name":"浙江龙盛","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600487" : {"name":"亨通光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"300498" : {"name":"温式股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601607" : {"name":"上海医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000651" : {"name":"格力电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000100" : {"name":"TCL集团 ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000063" : {"name":"中兴通信","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600570" : {"name":"恒生电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002074" : {"name":"国轩高科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
#   "603993" : {"name":"洛阳钼也","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600507" : {"name":"方大特钢","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601211" : {"name":"国泰君安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"601088" : {"name":"中国神华","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002594" : {"name":"比亚迪  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"002601" : {"name":"龙蟒百利","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600337" : {"name":"美克家居","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"300450" : {"name":"先导智能","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"000488" : {"name":"晨鸣纸业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"600309" : {"name":"万华化学","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	"300274" : {"name":"阳光电源","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
# 	
#     }

stock_pool = {
    #####################龙头股########################
    "002352" : {"name":"顺风控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002294" : {"name":"信立泰  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600887" : {"name":"伊利股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},     
    "600298" : {"name":"安琪酵母","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},    
    "000895" : {"name":"双汇集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600104" : {"name":"上汽集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600572" : {"name":"康恩贝  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600276" : {"name":"恒瑞医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600566" : {"name":"济川药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000538" : {"name":"云南白药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601318" : {"name":"中国平安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600056" : {"name":"中国医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "603288" : {"name":"海天味业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002027" : {"name":"分众传媒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000581" : {"name":"威孚高科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600741" : {"name":"华域汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000858" : {"name":"五粮液  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600519" : {"name":"贵州茅台","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002422" : {"name":"科伦药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002081" : {"name":"金螳螂  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002470" : {"name":"金正大  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002517" : {"name":"恺英网络","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300549" : {"name":"优德精密","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "603520" : {"name":"司立太  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600176" : {"name":"中国巨石","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002008" : {"name":"大族激光","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002745" : {"name":"木林森  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600585" : {"name":"海螺水泥","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002372" : {"name":"伟星新材","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600900" : {"name":"长江电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601006" : {"name":"大秦铁路","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600518" : {"name":"康美药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002202" : {"name":"金凤科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002310" : {"name":"东方园林","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000963" : {"name":"华东医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601933" : {"name":"永辉超市","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002466" : {"name":"天齐锂业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002475" : {"name":"立讯精密","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002241" : {"name":"歌尔股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600196" : {"name":"复星医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002572" : {"name":"索菲亚  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600816" : {"name":"安信信托","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002415" : {"name":"海康威视","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000333" : {"name":"美的集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002508" : {"name":"老板电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600660" : {"name":"福耀玻璃","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600201" : {"name":"生物股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000002" : {"name":"万科股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002450" : {"name":"康得新  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600009" : {"name":"上海机场","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600377" : {"name":"宁沪高速","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002597" : {"name":"金禾实业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601012" : {"name":"隆基股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000725" : {"name":"京东方  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600703" : {"name":"三安光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600699" : {"name":"均胜电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600036" : {"name":"招商银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601888" : {"name":"中国国旅","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600019" : {"name":"宝钢股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600352" : {"name":"浙江龙盛","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600487" : {"name":"亨通光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300498" : {"name":"温式股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601607" : {"name":"上海医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000651" : {"name":"格力电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000100" : {"name":"TCL集团 ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000063" : {"name":"中兴通信","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600570" : {"name":"恒生电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002074" : {"name":"国轩高科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "603993" : {"name":"洛阳钼也","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600507" : {"name":"方大特钢","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601211" : {"name":"国泰君安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "601088" : {"name":"中国神华","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002594" : {"name":"比亚迪  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002601" : {"name":"龙蟒百利","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600337" : {"name":"美克家居","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300450" : {"name":"先导智能","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000488" : {"name":"晨鸣纸业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "600309" : {"name":"万华化学","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300274" : {"name":"阳光电源","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},

    #####################深证100成分股####################
    "300498": { "name":"温氏股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300408": { "name":"三环集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300315": { "name":"掌趣科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300168": { "name":"万达信息","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300136": { "name":"信维通信","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300124": { "name":"汇川技术","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300104": { "name":"乐视网  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300072": { "name":"三聚环保","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300070": { "name":"碧水源  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300059": { "name":"东方财富","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300027": { "name":"华谊兄弟","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300024": { "name":"机器人  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "300017": { "name":"网宿科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002797": { "name":"第一创业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002739": { "name":"万达电影","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002736": { "name":"国信证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002709": { "name":"天赐材料","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002673": { "name":"西部证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002594": { "name":"比亚迪  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002558": { "name":"巨人网络","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002500": { "name":"山西证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002475": { "name":"立讯精密","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002466": { "name":"天齐锂业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002465": { "name":"海格通信","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002460": { "name":"赣锋锂业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002456": { "name":"欧菲光  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002450": { "name":"康得新  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002415": { "name":"海康威视","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002407": { "name":"多氟多  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002405": { "name":"四维图新","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002385": { "name":"大北农  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002352": { "name":"顺丰控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002340": { "name":"格林美  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002310": { "name":"东方园林","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002304": { "name":"洋河股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002292": { "name":"奥飞娱乐","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002252": { "name":"上海莱士","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002241": { "name":"歌尔股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002236": { "name":"大华股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002230": { "name":"科大讯飞","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002202": { "name":"金风科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002183": { "name":"怡 亚 通","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002142": { "name":"宁波银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002129": { "name":"中环股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002092": { "name":"中泰化学","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002081": { "name":"金 螳 螂","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002065": { "name":"东华软件","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002027": { "name":"分众传媒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002024": { "name":"苏宁云商","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002008": { "name":"大族激光","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "002007": { "name":"华兰生物","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "001979": { "name":"招商蛇口","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000983": { "name":"西山煤电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000963": { "name":"华东医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000961": { "name":"中南建设","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000938": { "name":"紫光股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000917": { "name":"电广传媒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000895": { "name":"双汇发展","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000876": { "name":"新 希 望","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000858": { "name":"五 粮 液","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000839": { "name":"中信国安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000826": { "name":"启迪桑德","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000793": { "name":"华闻传媒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000792": { "name":"盐湖股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000783": { "name":"长江证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000776": { "name":"广发证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000768": { "name":"中航飞机","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000750": { "name":"国海证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000738": { "name":"航发控制","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000728": { "name":"国元证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000725": { "name":"京东方Ａ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000709": { "name":"河钢股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000686": { "name":"东北证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000651": { "name":"格力电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000630": { "name":"铜陵有色","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000625": { "name":"长安汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000623": { "name":"吉林敖东","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000617": { "name":"中油资本","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000568": { "name":"泸州老窖","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000559": { "name":"万向钱潮","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000540": { "name":"中天金融","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000538": { "name":"云南白药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000503": { "name":"海虹控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000425": { "name":"徐工机械","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000423": { "name":"东阿阿胶","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000415": { "name":"渤海金控","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000413": { "name":"东旭光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000402": { "name":"金 融 街","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000338": { "name":"潍柴动力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000333": { "name":"美的集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000166": { "name":"申万宏源","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000157": { "name":"中联重科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000100": { "name":"TCL 集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None}, 
    "000069": { "name":"华侨城Ａ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000063": { "name":"中兴通讯","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000060": { "name":"中金岭南","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000046": { "name":"泛海控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000009": { "name":"中国宝安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000002": { "name":"万  科Ａ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    "000001": { "name":"平安银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},
    
    ########################上证180#######################################
    "603993": { "name":"洛阳钼业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "603858": { "name":"步长制药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "603777": { "name":"来伊份  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "603589": { "name":"口子窖  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "603444": { "name":"吉比特  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "601998": { "name":"中信银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601992": { "name":"金隅股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601989": { "name":"中国重工","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601988": { "name":"中国银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601985": { "name":"中国核电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601966": { "name":"玲珑轮胎","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601939": { "name":"建设银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601933": { "name":"永辉超市","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601919": { "name":"中远海控","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601901": { "name":"方正证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601899": { "name":"紫金矿业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601881": { "name":"中国银河","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601857": { "name":"中国石油","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601818": { "name":"光大银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601800": { "name":"中国交建","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601788": { "name":"光大证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601766": { "name":"中国中车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601727": { "name":"上海电气","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601718": { "name":"际华集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601699": { "name":"潞安环能","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601688": { "name":"华泰证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601669": { "name":"中国电建","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601668": { "name":"中国建筑","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601633": { "name":"长城汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601628": { "name":"中国人寿","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601618": { "name":"中国中冶","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601611": { "name":"中国核建","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601608": { "name":"中信重工","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601607": { "name":"上海医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601601": { "name":"中国太保","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601600": { "name":"中国铝业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601555": { "name":"东吴证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601398": { "name":"工商银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601390": { "name":"中国中铁","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601377": { "name":"兴业证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601336": { "name":"新华保险","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601328": { "name":"交通银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601318": { "name":"中国平安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601288": { "name":"农业银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601229": { "name":"上海银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601216": { "name":"君正集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601211": { "name":"国泰君安","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601198": { "name":"东兴证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601186": { "name":"中国铁建","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601169": { "name":"北京银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601166": { "name":"兴业银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601163": { "name":"三角轮胎","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601155": { "name":"新城控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601127": { "name":"小康股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601118": { "name":"海南橡胶","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601111": { "name":"中国国航","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601099": { "name":"太平洋  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "601088": { "name":"中国神华","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601018": { "name":"宁波港  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "601012": { "name":"隆基股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601009": { "name":"南京银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "601006": { "name":"大秦铁路","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600999": { "name":"招商证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600978": { "name":"宜华生活","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600977": { "name":"中国电影","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600958": { "name":"东方证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600926": { "name":"杭州银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600919": { "name":"江苏银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600909": { "name":"华安证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600900": { "name":"长江电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600895": { "name":"张江高科","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600893": { "name":"航发动力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600887": { "name":"伊利股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600886": { "name":"国投电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600873": { "name":"梅花生物","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600839": { "name":"四川长虹","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600837": { "name":"海通证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600827": { "name":"百联股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600820": { "name":"隧道股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600816": { "name":"安信信托","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600809": { "name":"山西汾酒","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600807": { "name":"天业股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600804": { "name":"鹏博士  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600795": { "name":"国电电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600773": { "name":"西藏城投","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600770": { "name":"综艺股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600741": { "name":"华域汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600739": { "name":"辽宁成大","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600737": { "name":"中粮糖业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600718": { "name":"东软集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600705": { "name":"中航资本","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600704": { "name":"物产中大","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600703": { "name":"三安光电","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600699": { "name":"均胜电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600690": { "name":"青岛海尔","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600688": { "name":"上海石化","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600663": { "name":"陆家嘴  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600649": { "name":"城投控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600645": { "name":"中源协和","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600643": { "name":"爱建集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600639": { "name":"浦东金桥","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600637": { "name":"东方明珠","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600606": { "name":"绿地控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600585": { "name":"海螺水泥","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600570": { "name":"恒生电子","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600565": { "name":"迪马股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600549": { "name":"厦门钨业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600547": { "name":"山东黄金","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600535": { "name":"天士力  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600528": { "name":"中铁工业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600522": { "name":"中天科技","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600519": { "name":"贵州茅台","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600518": { "name":"康美药业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600516": { "name":"方大炭素","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600503": { "name":"华丽家族","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600497": { "name":"驰宏锌锗","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600489": { "name":"中金黄金","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600485": { "name":"信威集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600482": { "name":"中国动力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600466": { "name":"蓝光发展","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600446": { "name":"金证股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600435": { "name":"北方导航","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600415": { "name":"小商品城","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600406": { "name":"国电南瑞","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600383": { "name":"金地集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600376": { "name":"首开股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600369": { "name":"西南证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600362": { "name":"江西铜业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600340": { "name":"华夏幸福","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600332": { "name":"白云山  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600315": { "name":"上海家化","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600297": { "name":"广汇汽车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600276": { "name":"恒瑞医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600271": { "name":"航天信息","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600266": { "name":"北京城建","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600233": { "name":"圆通速递","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600221": { "name":"海航控股","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600219": { "name":"南山铝业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600208": { "name":"新湖中宝","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600196": { "name":"复星医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600177": { "name":"雅戈尔  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600170": { "name":"上海建工","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600158": { "name":"中体产业","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600157": { "name":"永泰能源","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600153": { "name":"建发股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600150": { "name":"中国船舶","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600120": { "name":"浙江东方","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600118": { "name":"中国卫星","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600115": { "name":"东方航空","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600111": { "name":"北方稀土","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600109": { "name":"国金证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600104": { "name":"上汽集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600100": { "name":"同方股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600094": { "name":"大名城  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600089": { "name":"特变电工","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600085": { "name":"同仁堂  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600079": { "name":"人福医药","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600074": { "name":"保千里  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600068": { "name":"葛洲坝  ","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},  
    "600066": { "name":"宇通客车","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600061": { "name":"国投安信","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600060": { "name":"海信电器","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600050": { "name":"中国联通","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600048": { "name":"保利地产","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600037": { "name":"歌华有线","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600036": { "name":"招商银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600031": { "name":"三一重工","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600030": { "name":"中信证券","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600029": { "name":"南方航空","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600028": { "name":"中国石化","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600023": { "name":"浙能电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600021": { "name":"上海电力","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600019": { "name":"宝钢股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600018": { "name":"上港集团","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600016": { "name":"民生银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600015": { "name":"华夏银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600010": { "name":"包钢股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600009": { "name":"上海机场","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600008": { "name":"首创股份","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},   
    "600000": { "name":"浦发银行","index":False,"In":False,"15F_alert_time":None,"30F_alert_time":None, "60F_alert_time":None},      
    }


def get_stock_pool():
    return stock_pool

def get_stock_list():
    return stock_pool.keys()

def is_index(code_id):
    return stock_pool[code_id]["index"]
    
def update_alert_time(code_id,ktype):
    '''
    update alert time
    '''
    log.info("update alert time for " + code_id + " " + ktype)
    if "15" in ktype:
        stock_pool[code_id]["15F_alert_time"] = datetime.now()
    else:
        stock_pool[code_id]["30F_alert_time"] = datetime.now()

def get_stock_name(code_id):
    '''
    '''
    return stock_pool[code_id]["name"]

def get_alert_time(code_id,ktype):
    '''
    '''
    if "15" in ktype:
        return stock_pool[code_id]["15F_alert_time"]
    else:
        return stock_pool[code_id]["30F_alert_time"]
    
def is_alert_needed(code_id,ktype):
    '''
    we need to check if the alert email is sent recently
    '''
    if "15" in ktype:
        last_alert_time = stock_pool[code_id]["15F_alert_time"]
    elif "30" in ktype:
        last_alert_time = stock_pool[code_id]["30F_alert_time"]   
    elif "60" in ktype:
        last_alert_time = stock_pool[code_id]["60F_alert_time"]
    else:
        log.info("unknown ktype")
        exit(0)


    if last_alert_time is None:
        return True
    
    interval_time = datetime.now() - last_alert_time
    if interval_time.total_seconds() - get_alert_interval(ktype) > 0:
        return True
    else:
        return False

if __name__ == '__main__':
    pass